inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6.6
  Exclude:
    - ".git/**/*"
    - "public/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "db/**/*"
    - "bin/*"
    - "node_modules/node-sass/src/libsass/**/*"
    - "config/**/*"
    - "lib/tasks/*"
    - "vendor/**/*"
    - "path/ruby"
    - "spec/*"
    - "node_modules/**/*"
    - "app/uploaders/*"
    - "spec/factories/*"
    - "spec/models/product_spec.rb"
