default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: db
  socket: var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: lossPerori_development

test:
  <<: *default
  host: <%= ENV.fetch("DB_HOST") { 'localhost' } %>
  database: lossPerori_test

production:
  <<: *default
  database: lossPerori_production
  url: <%= ENV['JAWSDB_URL']&.sub('mysql://', 'mysql2://') %>
