default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: lossPerori_development

test:
  <<: *default
  database: docker_test
  username: test_root
  password: password
  host: <%= ENV.fetch("DB_HOST") { 'test-db' } %>

production:
  <<: *default
  database: lossPerori_production
  url: <%= ENV['JAWSDB_URL']&.sub('mysql://', 'mysql2://') %>
