default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: lossPerori_development

test:
  <<: *default
  username: test_root
  password: password
  database: docker_test
  host: 127.0.0.1

production:
  <<: *default
  database: lossPerori_production
  url: <%= ENV['JAWSDB_URL']&.sub('mysql://', 'mysql2://') %>
gd
